// <auto-generated />
using System;
using DormitoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DormitoryManagement.Migrations
{
    [DbContext(typeof(DormitoryContext))]
    partial class DormitoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DormitoryManagement.Data.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f251e7a-cc96-4b04-98b4-e24f313cdeaf"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "4d337c6c91099310b0d66d3c581e10ea958971eef83251a3a0c615f948cb8372"
                        },
                        new
                        {
                            Id = new Guid("c8729257-0e82-40b1-b2fb-5200c33f1ed2"),
                            Email = "jane.doe@example.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            PasswordHash = "0e4d12c8083054721084530af46bb793e61a4cf1227610f9ba8eb5e5f787866a"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14969e97-76fe-44a0-9ee0-6929b1d63191"),
                            Name = "Building A"
                        },
                        new
                        {
                            Id = new Guid("624d1900-4000-4288-bb7e-05aad525460c"),
                            Name = "Building B"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            BuildingId = new Guid("14969e97-76fe-44a0-9ee0-6929b1d63191"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            BuildingId = new Guid("14969e97-76fe-44a0-9ee0-6929b1d63191"),
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            BuildingId = new Guid("624d1900-4000-4288-bb7e-05aad525460c"),
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            BuildingId = new Guid("624d1900-4000-4288-bb7e-05aad525460c"),
                            Number = 2
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            Name = "Chair"
                        },
                        new
                        {
                            Id = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            Name = "Desk"
                        },
                        new
                        {
                            Id = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            Name = "Bed"
                        },
                        new
                        {
                            Id = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            Name = "Lamp"
                        },
                        new
                        {
                            Id = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            Name = "Bookshelf"
                        },
                        new
                        {
                            Id = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            Name = "Wardrobe"
                        },
                        new
                        {
                            Id = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            Name = "Curtains"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllowedPersons")
                        .HasColumnType("integer");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09d758c8-de0e-445f-aaba-00efd30cc95d"),
                            AllowedPersons = 4,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-01"
                        },
                        new
                        {
                            Id = new Guid("4fe434a3-e072-4d2a-86a4-0845eacad4e5"),
                            AllowedPersons = 5,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-02"
                        },
                        new
                        {
                            Id = new Guid("16f530e4-4ae3-4f2e-abb1-d25eee60aaf7"),
                            AllowedPersons = 3,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-03"
                        },
                        new
                        {
                            Id = new Guid("9e50ae24-ab61-4f9a-b0f4-1fd3d832e43b"),
                            AllowedPersons = 3,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-04"
                        },
                        new
                        {
                            Id = new Guid("b2a4aa88-6a16-4c5d-8d5f-07f262b17d6d"),
                            AllowedPersons = 5,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-05"
                        },
                        new
                        {
                            Id = new Guid("ad177cdb-96ea-4236-9f8e-dc7747439d94"),
                            AllowedPersons = 5,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-06"
                        },
                        new
                        {
                            Id = new Guid("0c1c77fe-ed23-4f0f-8e4e-274feb813a47"),
                            AllowedPersons = 5,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-07"
                        },
                        new
                        {
                            Id = new Guid("7ebeebec-644c-449c-ad0e-5fe6f998ff08"),
                            AllowedPersons = 4,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-08"
                        },
                        new
                        {
                            Id = new Guid("8a73eb50-c2df-41d8-88f8-2d3fa9bb8201"),
                            AllowedPersons = 4,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-09"
                        },
                        new
                        {
                            Id = new Guid("22d141f2-482e-413a-82d8-155e126b0c7b"),
                            AllowedPersons = 4,
                            FloorId = new Guid("5772ebaf-9330-4454-a348-1ddcec292d3d"),
                            Number = "A1-10"
                        },
                        new
                        {
                            Id = new Guid("cd9863d9-c2e1-4582-b69c-c74b5411406f"),
                            AllowedPersons = 3,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-01"
                        },
                        new
                        {
                            Id = new Guid("f4c42f77-0cdd-401e-b77e-afe2b9f349f2"),
                            AllowedPersons = 4,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-02"
                        },
                        new
                        {
                            Id = new Guid("cdfeb53d-0729-4f79-b703-7d70ac94e03a"),
                            AllowedPersons = 4,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-03"
                        },
                        new
                        {
                            Id = new Guid("5b5dd9f9-4d4b-47fc-9262-b014a89d1a4d"),
                            AllowedPersons = 3,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-04"
                        },
                        new
                        {
                            Id = new Guid("7fad5428-25fd-4a12-a2b6-87ed21eb2e01"),
                            AllowedPersons = 4,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-05"
                        },
                        new
                        {
                            Id = new Guid("6c461032-a612-454c-8ba6-f20bc862a241"),
                            AllowedPersons = 4,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-06"
                        },
                        new
                        {
                            Id = new Guid("82cb6d9f-fdd7-4e06-b037-39cfe3416605"),
                            AllowedPersons = 5,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-07"
                        },
                        new
                        {
                            Id = new Guid("81e50420-2a54-4727-bad6-e50350b9f6a9"),
                            AllowedPersons = 4,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-08"
                        },
                        new
                        {
                            Id = new Guid("33a2e0ee-8834-43c3-b9c9-8a0994a1d331"),
                            AllowedPersons = 3,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-09"
                        },
                        new
                        {
                            Id = new Guid("0658d770-508c-4122-a480-b628c04bbd14"),
                            AllowedPersons = 4,
                            FloorId = new Guid("d814ee59-793b-403c-8ac1-00978cdbe354"),
                            Number = "A2-10"
                        },
                        new
                        {
                            Id = new Guid("2714a3af-69a3-4b0e-8599-d32a5cc5d8c3"),
                            AllowedPersons = 3,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-01"
                        },
                        new
                        {
                            Id = new Guid("ce2c0784-7b42-4271-8f13-e95932057cc5"),
                            AllowedPersons = 5,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-02"
                        },
                        new
                        {
                            Id = new Guid("5a6c4841-8d60-4eed-bb70-71896f80bf0c"),
                            AllowedPersons = 3,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-03"
                        },
                        new
                        {
                            Id = new Guid("4c928ee3-6366-40f8-9ee6-93100e85bb58"),
                            AllowedPersons = 3,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-04"
                        },
                        new
                        {
                            Id = new Guid("bd2cd950-65e9-46ea-8bb2-746cec262a9e"),
                            AllowedPersons = 3,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-05"
                        },
                        new
                        {
                            Id = new Guid("ed7da385-1883-4e8a-9bcc-6b31c224b0a7"),
                            AllowedPersons = 5,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-06"
                        },
                        new
                        {
                            Id = new Guid("c42ba717-015f-4c8f-8350-8e91d230e4be"),
                            AllowedPersons = 5,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-07"
                        },
                        new
                        {
                            Id = new Guid("f3fd5baf-5430-4e9c-9387-26a0bcc053a8"),
                            AllowedPersons = 5,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-08"
                        },
                        new
                        {
                            Id = new Guid("253ae235-9a0c-44c3-8c25-b93fc1677407"),
                            AllowedPersons = 5,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-09"
                        },
                        new
                        {
                            Id = new Guid("0c02c93a-9d1c-4bb1-b324-0187b72b102c"),
                            AllowedPersons = 3,
                            FloorId = new Guid("ae28f8a0-f38d-4054-8398-2851c1eb9adb"),
                            Number = "B1-10"
                        },
                        new
                        {
                            Id = new Guid("aa1033b8-1e3e-4492-b8d7-680a96deb0a5"),
                            AllowedPersons = 4,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-01"
                        },
                        new
                        {
                            Id = new Guid("782cadc7-29a0-4a6a-bf88-f97ec7aee747"),
                            AllowedPersons = 3,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-02"
                        },
                        new
                        {
                            Id = new Guid("0024ef1c-059e-4eac-a68c-6ae615ca57ef"),
                            AllowedPersons = 4,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-03"
                        },
                        new
                        {
                            Id = new Guid("ba9dbcec-2ea7-4d71-aea8-f2f80a7eb5b4"),
                            AllowedPersons = 3,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-04"
                        },
                        new
                        {
                            Id = new Guid("53312856-4cee-450f-89dd-c9f94f58cd16"),
                            AllowedPersons = 5,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-05"
                        },
                        new
                        {
                            Id = new Guid("6b73c63d-5849-454b-8dd6-dabdd589adc9"),
                            AllowedPersons = 4,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-06"
                        },
                        new
                        {
                            Id = new Guid("8dc4ceaa-8eec-4c51-947a-c4566ed1430f"),
                            AllowedPersons = 5,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-07"
                        },
                        new
                        {
                            Id = new Guid("16d0e689-e827-49ba-9f66-fcaefcb81e92"),
                            AllowedPersons = 3,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-08"
                        },
                        new
                        {
                            Id = new Guid("2ef4548b-5c59-4c79-94f0-5ef7234be1ec"),
                            AllowedPersons = 5,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-09"
                        },
                        new
                        {
                            Id = new Guid("8cd34782-0561-449b-98e9-fc8d7d1fbf96"),
                            AllowedPersons = 5,
                            FloorId = new Guid("31544269-fe63-4ca0-bc6f-e435d563598e"),
                            Number = "B2-10"
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAssignments");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomInventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef8199d8-a9e2-407a-a5ca-c23f84eb86d3"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("09d758c8-de0e-445f-aaba-00efd30cc95d")
                        },
                        new
                        {
                            Id = new Guid("b6aacca4-4872-462b-87b9-5f7e59e4688b"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("09d758c8-de0e-445f-aaba-00efd30cc95d")
                        },
                        new
                        {
                            Id = new Guid("7bec88cf-66a8-4abe-9554-0e2f94ceb889"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("09d758c8-de0e-445f-aaba-00efd30cc95d")
                        },
                        new
                        {
                            Id = new Guid("98ff8d75-d2d0-4d2a-a096-79e70edff5aa"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("09d758c8-de0e-445f-aaba-00efd30cc95d")
                        },
                        new
                        {
                            Id = new Guid("7f74bdae-52bb-4b0e-8bcd-903a13cee825"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("4fe434a3-e072-4d2a-86a4-0845eacad4e5")
                        },
                        new
                        {
                            Id = new Guid("b31e635c-f58f-4345-9f0b-f972176fdb36"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("16f530e4-4ae3-4f2e-abb1-d25eee60aaf7")
                        },
                        new
                        {
                            Id = new Guid("862e838a-7eb9-436e-9526-c1388231ce20"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("16f530e4-4ae3-4f2e-abb1-d25eee60aaf7")
                        },
                        new
                        {
                            Id = new Guid("d992e0af-35ec-4cc8-b4f6-fb4487ab5d44"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("16f530e4-4ae3-4f2e-abb1-d25eee60aaf7")
                        },
                        new
                        {
                            Id = new Guid("38a6fbc6-f439-4e2c-9256-b069cc0ff3b7"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("16f530e4-4ae3-4f2e-abb1-d25eee60aaf7")
                        },
                        new
                        {
                            Id = new Guid("d7cac3b0-4297-4945-aa90-47b5107f59ca"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("9e50ae24-ab61-4f9a-b0f4-1fd3d832e43b")
                        },
                        new
                        {
                            Id = new Guid("c232c8fd-f9aa-460b-bf1e-66ab664df371"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("9e50ae24-ab61-4f9a-b0f4-1fd3d832e43b")
                        },
                        new
                        {
                            Id = new Guid("72564a4b-e1f3-4ab2-ab09-6c80fc90bc3f"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("b2a4aa88-6a16-4c5d-8d5f-07f262b17d6d")
                        },
                        new
                        {
                            Id = new Guid("53e8edec-cc2a-4207-8794-f022cf7d105e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("ad177cdb-96ea-4236-9f8e-dc7747439d94")
                        },
                        new
                        {
                            Id = new Guid("987cc216-950d-4787-9d42-47e9489735be"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("0c1c77fe-ed23-4f0f-8e4e-274feb813a47")
                        },
                        new
                        {
                            Id = new Guid("7dcf3c5d-e9ef-47b4-9f7f-8c40e4b2a646"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("0c1c77fe-ed23-4f0f-8e4e-274feb813a47")
                        },
                        new
                        {
                            Id = new Guid("da557f9b-5e3d-4f70-9c3c-67f80f446db9"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("0c1c77fe-ed23-4f0f-8e4e-274feb813a47")
                        },
                        new
                        {
                            Id = new Guid("c2df65cd-fb1d-44d6-abbf-40049bd342f3"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("0c1c77fe-ed23-4f0f-8e4e-274feb813a47")
                        },
                        new
                        {
                            Id = new Guid("5d2cf5ee-bffa-41d9-bbcd-adc03c0b59ff"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("0c1c77fe-ed23-4f0f-8e4e-274feb813a47")
                        },
                        new
                        {
                            Id = new Guid("50c00f1b-2ca0-40b2-90f9-cf755b6cc965"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("7ebeebec-644c-449c-ad0e-5fe6f998ff08")
                        },
                        new
                        {
                            Id = new Guid("b9aa5170-b237-4f80-9b6c-99828561e7aa"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("7ebeebec-644c-449c-ad0e-5fe6f998ff08")
                        },
                        new
                        {
                            Id = new Guid("bf75fcd2-78e6-45df-b30a-ca1d2c4cd7ab"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("7ebeebec-644c-449c-ad0e-5fe6f998ff08")
                        },
                        new
                        {
                            Id = new Guid("ee1c7ab1-6b0d-43ad-aefa-dce8ca03c727"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("7ebeebec-644c-449c-ad0e-5fe6f998ff08")
                        },
                        new
                        {
                            Id = new Guid("1687c17a-5e5f-40e4-81d3-8eef89eee566"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("7ebeebec-644c-449c-ad0e-5fe6f998ff08")
                        },
                        new
                        {
                            Id = new Guid("b19d55a4-e439-4cf8-8c50-94df5a1fd8a1"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("7ebeebec-644c-449c-ad0e-5fe6f998ff08")
                        },
                        new
                        {
                            Id = new Guid("9d0e9786-6974-4304-81ac-e372f7ec644a"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("8a73eb50-c2df-41d8-88f8-2d3fa9bb8201")
                        },
                        new
                        {
                            Id = new Guid("791f7968-6049-4bb1-a81b-e596243112bc"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("8a73eb50-c2df-41d8-88f8-2d3fa9bb8201")
                        },
                        new
                        {
                            Id = new Guid("088a95ad-a8b9-4a46-ac07-8f17ad6b1fd3"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("8a73eb50-c2df-41d8-88f8-2d3fa9bb8201")
                        },
                        new
                        {
                            Id = new Guid("171f3c3b-e47d-49a2-a18f-fdbfa03755ef"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("8a73eb50-c2df-41d8-88f8-2d3fa9bb8201")
                        },
                        new
                        {
                            Id = new Guid("22fc14d4-7c8f-4e00-882a-85558c61c02f"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("22d141f2-482e-413a-82d8-155e126b0c7b")
                        },
                        new
                        {
                            Id = new Guid("30b56e76-c4d9-4cb8-bdfe-4fd07790eeef"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("22d141f2-482e-413a-82d8-155e126b0c7b")
                        },
                        new
                        {
                            Id = new Guid("5c31e715-4575-444d-bf61-c93dd61c8251"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("22d141f2-482e-413a-82d8-155e126b0c7b")
                        },
                        new
                        {
                            Id = new Guid("ba1fce1b-fd4c-417d-91e4-2d5c785c385f"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("cd9863d9-c2e1-4582-b69c-c74b5411406f")
                        },
                        new
                        {
                            Id = new Guid("71077e86-0fa6-4a93-98aa-631c48579a18"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("cd9863d9-c2e1-4582-b69c-c74b5411406f")
                        },
                        new
                        {
                            Id = new Guid("8ae79b56-f8df-4adb-92e2-0f911ed81357"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("cd9863d9-c2e1-4582-b69c-c74b5411406f")
                        },
                        new
                        {
                            Id = new Guid("e3457602-25f2-465b-b273-78ed80d82f89"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("cd9863d9-c2e1-4582-b69c-c74b5411406f")
                        },
                        new
                        {
                            Id = new Guid("fd555c6a-5f8f-4e50-9e45-27e7ae820098"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("cd9863d9-c2e1-4582-b69c-c74b5411406f")
                        },
                        new
                        {
                            Id = new Guid("c180554f-c399-4d68-a0da-9a6ae2eaa51b"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("f4c42f77-0cdd-401e-b77e-afe2b9f349f2")
                        },
                        new
                        {
                            Id = new Guid("134f4fa2-f3bc-49da-976e-0f9d444f98eb"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("f4c42f77-0cdd-401e-b77e-afe2b9f349f2")
                        },
                        new
                        {
                            Id = new Guid("7a15995d-a8ce-4473-8bbe-1760764c2f1c"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("cdfeb53d-0729-4f79-b703-7d70ac94e03a")
                        },
                        new
                        {
                            Id = new Guid("e41a24f2-ee43-4c9e-82cb-228305c6addd"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("cdfeb53d-0729-4f79-b703-7d70ac94e03a")
                        },
                        new
                        {
                            Id = new Guid("97444a89-e6ef-4c65-8753-4b7c6d6f394d"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("cdfeb53d-0729-4f79-b703-7d70ac94e03a")
                        },
                        new
                        {
                            Id = new Guid("05aad1a5-4655-47a6-a79f-b7828fba801d"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("cdfeb53d-0729-4f79-b703-7d70ac94e03a")
                        },
                        new
                        {
                            Id = new Guid("54d3665f-8e85-4a4d-9b25-c205a5dc260e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("cdfeb53d-0729-4f79-b703-7d70ac94e03a")
                        },
                        new
                        {
                            Id = new Guid("43053dd0-f7e7-4c93-81d7-013a9df7a0a6"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("cdfeb53d-0729-4f79-b703-7d70ac94e03a")
                        },
                        new
                        {
                            Id = new Guid("b553c631-3ff6-4b80-aa9e-ec77a068aa5d"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("5b5dd9f9-4d4b-47fc-9262-b014a89d1a4d")
                        },
                        new
                        {
                            Id = new Guid("e32ab879-c249-4d33-a8d0-2a3844fbc34c"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("5b5dd9f9-4d4b-47fc-9262-b014a89d1a4d")
                        },
                        new
                        {
                            Id = new Guid("d82484a7-a930-4e23-bce3-08d6117d04d5"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("5b5dd9f9-4d4b-47fc-9262-b014a89d1a4d")
                        },
                        new
                        {
                            Id = new Guid("d5d32350-d70d-4f80-b002-c8d245dff300"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("7fad5428-25fd-4a12-a2b6-87ed21eb2e01")
                        },
                        new
                        {
                            Id = new Guid("9a26d7a7-ff1a-40e0-89fa-c44c38190cea"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("7fad5428-25fd-4a12-a2b6-87ed21eb2e01")
                        },
                        new
                        {
                            Id = new Guid("60e7ba7f-968d-4672-8afd-fcf1078fef9f"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("6c461032-a612-454c-8ba6-f20bc862a241")
                        },
                        new
                        {
                            Id = new Guid("b5cb3c3b-0594-45ab-aa09-a66fb778083d"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("6c461032-a612-454c-8ba6-f20bc862a241")
                        },
                        new
                        {
                            Id = new Guid("f3674da6-f0d3-406e-bd58-14e44707a63a"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("82cb6d9f-fdd7-4e06-b037-39cfe3416605")
                        },
                        new
                        {
                            Id = new Guid("2adad499-01fa-4074-85a3-4cfba9312d84"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("82cb6d9f-fdd7-4e06-b037-39cfe3416605")
                        },
                        new
                        {
                            Id = new Guid("a02179b6-e527-4534-b33f-b9d7bb2bd337"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("82cb6d9f-fdd7-4e06-b037-39cfe3416605")
                        },
                        new
                        {
                            Id = new Guid("203fb690-8d69-4986-b5c0-2f9f9ade4f47"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("82cb6d9f-fdd7-4e06-b037-39cfe3416605")
                        },
                        new
                        {
                            Id = new Guid("86bcb23b-b0d0-4c0d-bd60-44ec768e5da3"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("82cb6d9f-fdd7-4e06-b037-39cfe3416605")
                        },
                        new
                        {
                            Id = new Guid("a4af5ada-e12c-42ac-842e-f8c9a80a2cb5"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("82cb6d9f-fdd7-4e06-b037-39cfe3416605")
                        },
                        new
                        {
                            Id = new Guid("4ae3796c-3efc-45e5-a0aa-e3099b9bf926"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("81e50420-2a54-4727-bad6-e50350b9f6a9")
                        },
                        new
                        {
                            Id = new Guid("07456be3-9884-4419-84bd-9dcd9a1a3c50"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("81e50420-2a54-4727-bad6-e50350b9f6a9")
                        },
                        new
                        {
                            Id = new Guid("6ae47987-39a2-4538-98a8-02ff6af4fba7"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("81e50420-2a54-4727-bad6-e50350b9f6a9")
                        },
                        new
                        {
                            Id = new Guid("d6fa4a83-2f72-4615-abb8-d4d905066926"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("81e50420-2a54-4727-bad6-e50350b9f6a9")
                        },
                        new
                        {
                            Id = new Guid("2fd01864-adaa-42f0-be50-7cf76ccd8c73"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("81e50420-2a54-4727-bad6-e50350b9f6a9")
                        },
                        new
                        {
                            Id = new Guid("b67bffa1-3b82-4cc7-8dd6-234d99820fc9"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("33a2e0ee-8834-43c3-b9c9-8a0994a1d331")
                        },
                        new
                        {
                            Id = new Guid("e4534556-1f30-459c-b419-967d5459292e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("0658d770-508c-4122-a480-b628c04bbd14")
                        },
                        new
                        {
                            Id = new Guid("2d95f5d0-33a7-4db1-a7aa-08f6ebcbacb3"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("0658d770-508c-4122-a480-b628c04bbd14")
                        },
                        new
                        {
                            Id = new Guid("ccbbedec-796e-4b73-9bd9-ceebc1334994"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("0658d770-508c-4122-a480-b628c04bbd14")
                        },
                        new
                        {
                            Id = new Guid("22b06dcb-a757-411d-9b74-aebfe24368e6"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("0658d770-508c-4122-a480-b628c04bbd14")
                        },
                        new
                        {
                            Id = new Guid("51dda55b-8c6a-4a9d-8b48-da9ac94d6c19"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("0658d770-508c-4122-a480-b628c04bbd14")
                        },
                        new
                        {
                            Id = new Guid("4820ccd3-b2e1-42b4-b50d-f47d02340f2d"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("2714a3af-69a3-4b0e-8599-d32a5cc5d8c3")
                        },
                        new
                        {
                            Id = new Guid("8560758e-51e3-4991-88e0-dc32331711dd"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("2714a3af-69a3-4b0e-8599-d32a5cc5d8c3")
                        },
                        new
                        {
                            Id = new Guid("643b20df-51b6-4222-bbdf-2da77e1d26b6"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("2714a3af-69a3-4b0e-8599-d32a5cc5d8c3")
                        },
                        new
                        {
                            Id = new Guid("0029a6d3-bedd-4a25-9a81-aeae8959dd87"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("2714a3af-69a3-4b0e-8599-d32a5cc5d8c3")
                        },
                        new
                        {
                            Id = new Guid("066f0e7a-4b8c-422e-bd2b-e42a5a504af7"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("2714a3af-69a3-4b0e-8599-d32a5cc5d8c3")
                        },
                        new
                        {
                            Id = new Guid("f4da95c6-57ef-47f8-864c-4eac4a981c5f"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("2714a3af-69a3-4b0e-8599-d32a5cc5d8c3")
                        },
                        new
                        {
                            Id = new Guid("0e1075cd-d911-4b93-ab83-8c3b2942421f"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("ce2c0784-7b42-4271-8f13-e95932057cc5")
                        },
                        new
                        {
                            Id = new Guid("5c8ae99a-d404-4852-b7b6-e6079136db0b"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("ce2c0784-7b42-4271-8f13-e95932057cc5")
                        },
                        new
                        {
                            Id = new Guid("dc635b5f-de13-4b4f-ade0-83a25c498697"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("5a6c4841-8d60-4eed-bb70-71896f80bf0c")
                        },
                        new
                        {
                            Id = new Guid("79923d92-2b5d-43ec-8b29-6b93214eb767"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("5a6c4841-8d60-4eed-bb70-71896f80bf0c")
                        },
                        new
                        {
                            Id = new Guid("62abe065-661a-4125-91d9-c1092ec8e81d"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("4c928ee3-6366-40f8-9ee6-93100e85bb58")
                        },
                        new
                        {
                            Id = new Guid("35209758-24a9-4dec-a8b6-a5d4c5607dc6"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("4c928ee3-6366-40f8-9ee6-93100e85bb58")
                        },
                        new
                        {
                            Id = new Guid("456451a9-3358-4ec6-8ce8-18907d3a8d5c"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("4c928ee3-6366-40f8-9ee6-93100e85bb58")
                        },
                        new
                        {
                            Id = new Guid("e2e49048-8202-4203-8428-f86b373b5ca3"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("4c928ee3-6366-40f8-9ee6-93100e85bb58")
                        },
                        new
                        {
                            Id = new Guid("03bd570a-7e2a-4c0c-a98c-0226580e5b62"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("4c928ee3-6366-40f8-9ee6-93100e85bb58")
                        },
                        new
                        {
                            Id = new Guid("524939bc-c69f-4870-945f-555a145b7b42"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("4c928ee3-6366-40f8-9ee6-93100e85bb58")
                        },
                        new
                        {
                            Id = new Guid("db0557d0-ee63-4928-a7e0-36678d928d3f"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("bd2cd950-65e9-46ea-8bb2-746cec262a9e")
                        },
                        new
                        {
                            Id = new Guid("120961b9-f60d-4ab7-8162-ca0da5053e55"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("bd2cd950-65e9-46ea-8bb2-746cec262a9e")
                        },
                        new
                        {
                            Id = new Guid("5e0eee73-ec56-4da9-9886-e31a052a478a"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("bd2cd950-65e9-46ea-8bb2-746cec262a9e")
                        },
                        new
                        {
                            Id = new Guid("b5dd4a68-81b2-413d-adab-6d1baadf9666"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("ed7da385-1883-4e8a-9bcc-6b31c224b0a7")
                        },
                        new
                        {
                            Id = new Guid("71f56864-c6e1-4454-b136-ad3170f55c3f"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("ed7da385-1883-4e8a-9bcc-6b31c224b0a7")
                        },
                        new
                        {
                            Id = new Guid("2673a5df-f471-469c-a986-5bdf98f3c681"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("ed7da385-1883-4e8a-9bcc-6b31c224b0a7")
                        },
                        new
                        {
                            Id = new Guid("6bc1d125-18e5-4f69-b57c-4897bc13065d"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("c42ba717-015f-4c8f-8350-8e91d230e4be")
                        },
                        new
                        {
                            Id = new Guid("13056941-712d-4ac6-91df-65313aa8bcec"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("f3fd5baf-5430-4e9c-9387-26a0bcc053a8")
                        },
                        new
                        {
                            Id = new Guid("25796d0e-9050-450c-b52c-88958fbbf8b6"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("f3fd5baf-5430-4e9c-9387-26a0bcc053a8")
                        },
                        new
                        {
                            Id = new Guid("8476f6c4-c9d0-4ae7-bfbd-cbef78bb9757"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("f3fd5baf-5430-4e9c-9387-26a0bcc053a8")
                        },
                        new
                        {
                            Id = new Guid("ffdbb3a7-92a6-430c-a1d9-14e2adb8132c"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("253ae235-9a0c-44c3-8c25-b93fc1677407")
                        },
                        new
                        {
                            Id = new Guid("fb6d8252-e867-4b20-8b8b-fff086a0bbd1"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("253ae235-9a0c-44c3-8c25-b93fc1677407")
                        },
                        new
                        {
                            Id = new Guid("cb4fe895-64ff-4d4d-a901-50903ded794b"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("0c02c93a-9d1c-4bb1-b324-0187b72b102c")
                        },
                        new
                        {
                            Id = new Guid("0c63001b-f1ce-4423-aa3c-99f607df5ac3"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("0c02c93a-9d1c-4bb1-b324-0187b72b102c")
                        },
                        new
                        {
                            Id = new Guid("b1145e7b-97de-47fe-9f79-ed630178592f"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("0c02c93a-9d1c-4bb1-b324-0187b72b102c")
                        },
                        new
                        {
                            Id = new Guid("15913001-35c7-42b7-a255-061dfb4cf199"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("0c02c93a-9d1c-4bb1-b324-0187b72b102c")
                        },
                        new
                        {
                            Id = new Guid("291c1780-fe99-43ac-970d-bae8c82defb9"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("0c02c93a-9d1c-4bb1-b324-0187b72b102c")
                        },
                        new
                        {
                            Id = new Guid("c9a1f8a8-162a-4102-a5f8-10a82643c0ef"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("0c02c93a-9d1c-4bb1-b324-0187b72b102c")
                        },
                        new
                        {
                            Id = new Guid("b6e29518-e91b-4c29-8736-018c197d6e35"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("aa1033b8-1e3e-4492-b8d7-680a96deb0a5")
                        },
                        new
                        {
                            Id = new Guid("050e9912-c6cf-4460-a44e-d9b37d2242bc"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("aa1033b8-1e3e-4492-b8d7-680a96deb0a5")
                        },
                        new
                        {
                            Id = new Guid("e1090f7b-9abf-4622-a951-c5bf269b6bfd"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("aa1033b8-1e3e-4492-b8d7-680a96deb0a5")
                        },
                        new
                        {
                            Id = new Guid("f046e37e-4c44-4137-a271-2d6cee7ae20f"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("aa1033b8-1e3e-4492-b8d7-680a96deb0a5")
                        },
                        new
                        {
                            Id = new Guid("ccc591c1-17c2-4f7a-bf69-821dd75f857d"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("aa1033b8-1e3e-4492-b8d7-680a96deb0a5")
                        },
                        new
                        {
                            Id = new Guid("2193ef19-138b-4e8b-89b1-26b4e0e18651"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("782cadc7-29a0-4a6a-bf88-f97ec7aee747")
                        },
                        new
                        {
                            Id = new Guid("f29840ab-baaa-4726-80e9-91036bbd308c"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("782cadc7-29a0-4a6a-bf88-f97ec7aee747")
                        },
                        new
                        {
                            Id = new Guid("cc2d7d43-c00c-4e52-8d3f-1e12c52a4d26"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("782cadc7-29a0-4a6a-bf88-f97ec7aee747")
                        },
                        new
                        {
                            Id = new Guid("aed562a0-0b8b-402a-a498-7092356ef220"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("782cadc7-29a0-4a6a-bf88-f97ec7aee747")
                        },
                        new
                        {
                            Id = new Guid("b7a2fe25-3416-4d89-8117-ae0602df8165"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("0024ef1c-059e-4eac-a68c-6ae615ca57ef")
                        },
                        new
                        {
                            Id = new Guid("5963ca1a-c8ce-4677-a0b1-d52ebf4b7239"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("0024ef1c-059e-4eac-a68c-6ae615ca57ef")
                        },
                        new
                        {
                            Id = new Guid("f973592d-f1cb-4262-ae2f-f42217210d21"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("0024ef1c-059e-4eac-a68c-6ae615ca57ef")
                        },
                        new
                        {
                            Id = new Guid("58eb9320-9904-4e0d-985d-5f608ea5d796"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("0024ef1c-059e-4eac-a68c-6ae615ca57ef")
                        },
                        new
                        {
                            Id = new Guid("18097f5e-0074-4c9c-b750-0b48144fe50b"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("0024ef1c-059e-4eac-a68c-6ae615ca57ef")
                        },
                        new
                        {
                            Id = new Guid("a463614d-93ef-4194-92d0-5b12875adfab"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("ba9dbcec-2ea7-4d71-aea8-f2f80a7eb5b4")
                        },
                        new
                        {
                            Id = new Guid("1068967e-ce27-408c-8b1a-45e7f572a97d"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("ba9dbcec-2ea7-4d71-aea8-f2f80a7eb5b4")
                        },
                        new
                        {
                            Id = new Guid("da182319-b117-42f3-91b9-d090b7f09f7e"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("ba9dbcec-2ea7-4d71-aea8-f2f80a7eb5b4")
                        },
                        new
                        {
                            Id = new Guid("b5b8a197-d8e1-485c-97b8-c42f104bdff5"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("b2f00ff7-591c-4e45-964e-c1dd03ce2134"),
                            RoomId = new Guid("ba9dbcec-2ea7-4d71-aea8-f2f80a7eb5b4")
                        },
                        new
                        {
                            Id = new Guid("3603e847-de8f-4e47-827a-e86228b8347b"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("ba9dbcec-2ea7-4d71-aea8-f2f80a7eb5b4")
                        },
                        new
                        {
                            Id = new Guid("260b2303-2af5-447f-ba0b-596b2e2d9821"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("53312856-4cee-450f-89dd-c9f94f58cd16")
                        },
                        new
                        {
                            Id = new Guid("8bede690-a1a5-4741-beed-71984c634c90"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("6b73c63d-5849-454b-8dd6-dabdd589adc9")
                        },
                        new
                        {
                            Id = new Guid("0ad6406a-8f08-47e5-8884-cfca2a7ec72a"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 1,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("8dc4ceaa-8eec-4c51-947a-c4566ed1430f")
                        },
                        new
                        {
                            Id = new Guid("2cdc2730-0900-4d9a-a2e0-61d236578f37"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("16d0e689-e827-49ba-9f66-fcaefcb81e92")
                        },
                        new
                        {
                            Id = new Guid("bf5ba8a3-b563-4fa4-b027-072b6bf4640c"),
                            ActualQuantity = 1,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("16d0e689-e827-49ba-9f66-fcaefcb81e92")
                        },
                        new
                        {
                            Id = new Guid("0ec5216a-87e5-4bc1-a34a-3b62def725fd"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("2d36531b-1ceb-4b47-b469-a7bc6f9049c0"),
                            RoomId = new Guid("2ef4548b-5c59-4c79-94f0-5ef7234be1ec")
                        },
                        new
                        {
                            Id = new Guid("74432f18-da8b-4674-86b3-f5e6735a4f6e"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("5c58d892-cf1b-4e66-84de-b68ac8b81583"),
                            RoomId = new Guid("2ef4548b-5c59-4c79-94f0-5ef7234be1ec")
                        },
                        new
                        {
                            Id = new Guid("605227a7-3881-4f0b-8461-37b2b055c98d"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("1bc99984-7f63-4642-b005-0aab23caed86"),
                            RoomId = new Guid("2ef4548b-5c59-4c79-94f0-5ef7234be1ec")
                        },
                        new
                        {
                            Id = new Guid("c68fd777-a7a8-4ad9-b719-f94c494ee9db"),
                            ActualQuantity = 3,
                            ExpectedQuantity = 3,
                            InventoryItemId = new Guid("7a22f39e-efa4-4ca1-8dae-1ae8b6aeb7d2"),
                            RoomId = new Guid("8cd34782-0561-449b-98e9-fc8d7d1fbf96")
                        },
                        new
                        {
                            Id = new Guid("ce8d8e1c-5b0a-42e0-9810-dac5561900db"),
                            ActualQuantity = 4,
                            ExpectedQuantity = 4,
                            InventoryItemId = new Guid("998523fb-9507-4db2-a0aa-971a0bf3d86f"),
                            RoomId = new Guid("8cd34782-0561-449b-98e9-fc8d7d1fbf96")
                        },
                        new
                        {
                            Id = new Guid("f6287997-1284-4c12-ab4f-cfd33d218f9c"),
                            ActualQuantity = 2,
                            ExpectedQuantity = 2,
                            InventoryItemId = new Guid("219caaee-16ad-4205-a906-e7c190339d63"),
                            RoomId = new Guid("8cd34782-0561-449b-98e9-fc8d7d1fbf96")
                        });
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitialPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoomAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomAssignmentId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("StudentId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomAssignment", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Room", "Room")
                        .WithMany("RoomAssignments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomInventory", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormitoryManagement.Data.Models.Room", "Room")
                        .WithMany("RoomInventories")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Student", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.RoomAssignment", "RoomAssignment")
                        .WithOne("Student")
                        .HasForeignKey("DormitoryManagement.Data.Models.Student", "RoomAssignmentId");

                    b.Navigation("RoomAssignment");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Ticket", b =>
                {
                    b.HasOne("DormitoryManagement.Data.Models.Room", "Room")
                        .WithMany("Tickets")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DormitoryManagement.Data.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.Room", b =>
                {
                    b.Navigation("RoomAssignments");

                    b.Navigation("RoomInventories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("DormitoryManagement.Data.Models.RoomAssignment", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
